language: python
python:
  - "3.6"
  - "pypy3.5"
before_script:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - export PATH=/home/travis/miniconda/bin:$PATH
install:
  - sudo apt-get update
  - python setup.py install
script:
- nosetests  --with-coverage --cover-package=swell -v
after_success: # Generate coverage reports only on success
  - coveralls
