language: python
python:
  - "3.6"
  # PyPy versions
  - "pypy3.5"
# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get -y install numpy
  - python setup.py install
script:
  - nosetests -v
