language: python
python:
  - "3.6"
  - "pypy3.5"

before_install:
  - if [ ${TRAVIS_PYTHON_VERSION:0:1} == "2" ]; then wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh; else wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/mc
- export PATH=/home/travis/mc/bin:$PATH

install:
  - conda update --yes conda

  # for debugging...
  - echo $PATH
  - which python
  - conda info
  - python setup.py install


script:
  - nosetests -v
