language: python
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
install:
  - sudo apt-get update
  - sudo apt-get -y install python-dev python-pip
  - python setup.py install
  - pip install requests bs4 coveralls
script:
  - nosetests  --with-coverage --cover-package=swel -v
  #- pytest -v --cov=swel
after_success: # Generate coverage reports only on success
  - coveralls

notifications:
  email: true

deploy: # Runs on every commit to master branch
  # test pypi
  - provider: pypi
    server: https://test.pypi.org/legacy/ 
    user: geoncs
    password:
        secure: "mRJulNnxw6FGQOF541d4RoKi5qArUGyqFQmmJ6vz4xGfMB0+2loHdy+yo8tyEIJ8QY8dVM4p1OKyBtSiFcNVDUjwTP4JBhmd9F03RSq429p1VmIrR1RPCXuhCOp736BL7bbOvNCoeXosxpY0FEiy/7qGmwvnnw6PxinTVKKvYFaNxDyoqRzdSuoQa5VXOKCk3BVxZQIjMbTGx9IlOW5swRDoGuYUwDdxeGS31H+JU9xnB0CKUnGM4PE2GA4D7CE/dpUM1/hch9neQcizRaIxLy/Yycj3HfKyzTOTmigx1aWx8RcX+xz5uvZYCZxPtBmC1+LlnFEVYcDh8vG8BqGjIbpVJfYYdU3/F0V9Gl/F9h2Ic3B1xM+32M1/QKuGORUclXt+UhFyjC3RNYb3b/fcNoc2FbUWauV0n2ukRItCyADVVufMppDZsa3dqFi1kDO3VqUO4YgnfSSE5BKKpAttt5E6OmyGZWOrgLQnrq5QW6PhERqQAvnUwmStEKwfa9Ra6OPagxWsicbLOo+mV6hylPJ9m2hLjL8wXJ9WUtu9s4lU1otqIwIQzPGI16AehLj9HHTTrpIioNLgjQb097ecOWMIMXAG7JUnOdI7E4jELXzmudRijm8bVOt/UgcqT2PeypIMg11hQZByTnBpHFXKB+YOckBMSQ0ppHRfTlegxxM="
    skip_existing: true
    on:
        branch: master
        tags: false

  # Runs only on tagged commits to master branch
  - provider: pypi
    user: geoncs
    password:
        secure: "rS40mY+GVsLftKLQ9exSKfqh9RvH23mZmIxSCq1gUna/3mAdAPXLF9je/jzHyxJQuO6WU42U9mRc+opqYe4FUBwxfu4HwsOxd/nOYEcmXADvDOBLwmLl0/63GyjArDTpaI6o8Pbg5qISn6Xkrc5nrwndmjEgWgIOKkWiIWB1ZU8bZgcNqN/6ukJ8ef/mMbThrQYMGQTaZ+ZKtf2sTSrrSTvZ1e10wGG8xUwkoyMgaId409wtqzZDQuRNS4YOiJ/CWya+m7bU9p40S4vn6+068Z0PvfGHo6llEkERpl8yMmHrEzCwtDZTM4iA9cKt/n/gMqTRpq9ifJtosDyHpZRhVhBaALjZkHsHAR8gjbuOqcRzqQzAJJjsHryZVw1EEhL/G4xPQ+U9zDwMD1ibq1Zb60/MhSSNhmc3O15swGWEXanOvgn0ubXsKovU/vzE2DW4U7J5l56KwDM1ZrqT/3AYB84YaOc3S/XLRfHR1PJIVdj5VAukrk+ey7YBK3VObQNOl2I0ImasWvvVmMc/XXhegyrLPoT5BU8MnpNQH5rNB2CPKJBQDV550M9DwmvL2Db6VpGZHHLzrfeMe6sROELEWJzAr/mTVOoFiRxKmLmeRfjkKm9EsN2ISbzRyK2nFHyE+wQ16+wZ50SjyRJL+zqEiDlzBJTnLDXGSoyaq1homRo="
    distributions: sdist bdist_wheel
    on:
        tags: true
        branch: master
    skip_existing: true
