language: python
matrix:
  include:
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
install:
  - sudo apt-get update
  - sudo apt-get -y install python-dev python-pip
  - python setup.py install
  - pip install requests bs4 coveralls
script:
  - nosetests  --with-coverage --cover-package=swel -v
  #- pytest -v --cov=swel.buoy
after_success: # Generate coverage reports only on success
  - coveralls

notifications:
  email: true
